server:
  port: 8888
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/MyWebServer?characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  # mapper映射文件所在的包
  mapper-locations: classpath:/mapper/*.xml
  # 实体类所在的包
  type-aliases-package: com.lty.pojo
  configuration:
    # 将下划线映射成驼峰
    map-underscore-to-camel-case: true
    # 开启延迟加载
    lazy-loading-enabled: true
    # 按需加载关闭
    aggressive-lazy-loading: false
    log-impl: org.apache.ibatis.logging.log4j.Log4jImpl
